/* Generated by Yosys 0.50+56 (git sha1 78960292d, x86_64-w64-mingw32-g++ 13.2.1 -O3) */

(* top =  1  *)
(* src = "Multiplier.sv:23.1-34.10" *)
module Multiplier(a, b, s);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  (* src = "Multiplier.sv:25.18-25.19" *)
  input [0:3] a;
  wire [0:3] a;
  (* src = "Multiplier.sv:26.18-26.19" *)
  input [0:3] b;
  wire [0:3] b;
  (* src = "Multiplier.sv:28.19-28.20" *)
  output [0:3] s;
  wire [0:3] s;
  assign _00_ = a[2] & b[3];
  assign _01_ = ~(b[2] & a[3]);
  assign s[2] = ~(_01_ ^ _00_);
  assign _02_ = ~(b[3] & a[1]);
  assign _03_ = ~(a[2] & b[2]);
  assign _04_ = ~(_03_ ^ _02_);
  assign _05_ = ~(b[1] & a[3]);
  assign _06_ = ~(_05_ ^ _04_);
  assign _07_ = _01_ | ~(_00_);
  assign s[1] = _07_ ^ _06_;
  assign _08_ = a[0] & b[3];
  assign _09_ = b[2] & a[1];
  assign _10_ = ~(_09_ ^ _08_);
  assign _11_ = b[1] & a[2];
  assign _12_ = ~(_11_ ^ _10_);
  assign _13_ = ~(_03_ | _02_);
  assign _14_ = ~(_05_ | _04_);
  assign _15_ = ~(_14_ | _13_);
  assign _16_ = ~(_15_ ^ _12_);
  assign _17_ = b[0] & a[3];
  assign _18_ = ~(_17_ ^ _16_);
  assign _19_ = ~(_07_ | _06_);
  assign s[0] = ~(_19_ ^ _18_);
  assign s[3] = a[3] & b[3];
endmodule
