/* Generated by Yosys 0.50+56 (git sha1 78960292d, x86_64-w64-mingw32-g++ 13.2.1 -O3) */

(* src = "Sources\\XOR.v:3.1-47.10" *)
module xor_chain(A, B, D, F, H, J, L, N, P, C, E, G, I, K, M, O, Q);
  (* src = "Sources\\XOR.v:4.17-4.18" *)
  wire _00_;
  (* src = "Sources\\XOR.v:5.17-5.18" *)
  wire _01_;
  (* src = "Sources\\XOR.v:13.17-13.18" *)
  wire _02_;
  (* src = "Sources\\XOR.v:6.17-6.18" *)
  wire _03_;
  (* src = "Sources\\XOR.v:14.17-14.18" *)
  wire _04_;
  (* src = "Sources\\XOR.v:7.17-7.18" *)
  wire _05_;
  (* src = "Sources\\XOR.v:15.17-15.18" *)
  wire _06_;
  (* src = "Sources\\XOR.v:8.17-8.18" *)
  wire _07_;
  (* src = "Sources\\XOR.v:16.17-16.18" *)
  wire _08_;
  (* src = "Sources\\XOR.v:9.17-9.18" *)
  wire _09_;
  (* src = "Sources\\XOR.v:17.17-17.18" *)
  wire _10_;
  (* src = "Sources\\XOR.v:10.17-10.18" *)
  wire _11_;
  (* src = "Sources\\XOR.v:18.17-18.18" *)
  wire _12_;
  (* src = "Sources\\XOR.v:11.17-11.18" *)
  wire _13_;
  (* src = "Sources\\XOR.v:19.17-19.18" *)
  wire _14_;
  (* src = "Sources\\XOR.v:12.17-12.18" *)
  wire _15_;
  (* src = "Sources\\XOR.v:20.17-20.18" *)
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  wire _31_;
  wire _32_;
  wire _33_;
  wire _34_;
  wire _35_;
  wire _36_;
  wire _37_;
  wire _38_;
  wire _39_;
  wire _40_;
  wire _41_;
  wire _42_;
  (* src = "Sources\\XOR.v:4.17-4.18" *)
  input A;
  wire A;
  (* src = "Sources\\XOR.v:5.17-5.18" *)
  input B;
  wire B;
  (* src = "Sources\\XOR.v:13.17-13.18" *)
  output C;
  wire C;
  (* src = "Sources\\XOR.v:6.17-6.18" *)
  input D;
  wire D;
  (* src = "Sources\\XOR.v:14.17-14.18" *)
  output E;
  wire E;
  (* src = "Sources\\XOR.v:7.17-7.18" *)
  input F;
  wire F;
  (* src = "Sources\\XOR.v:15.17-15.18" *)
  output G;
  wire G;
  (* src = "Sources\\XOR.v:8.17-8.18" *)
  input H;
  wire H;
  (* src = "Sources\\XOR.v:16.17-16.18" *)
  output I;
  wire I;
  (* src = "Sources\\XOR.v:9.17-9.18" *)
  input J;
  wire J;
  (* src = "Sources\\XOR.v:17.17-17.18" *)
  output K;
  wire K;
  (* src = "Sources\\XOR.v:10.17-10.18" *)
  input L;
  wire L;
  (* src = "Sources\\XOR.v:18.17-18.18" *)
  output M;
  wire M;
  (* src = "Sources\\XOR.v:11.17-11.18" *)
  input N;
  wire N;
  (* src = "Sources\\XOR.v:19.17-19.18" *)
  output O;
  wire O;
  (* src = "Sources\\XOR.v:12.17-12.18" *)
  input P;
  wire P;
  (* src = "Sources\\XOR.v:20.17-20.18" *)
  output Q;
  wire Q;
  assign _17_ = _01_ | _00_;
  assign _18_ = ~(_01_ & _00_);
  assign _19_ = ~(_17_ & _18_);
  assign _02_ = ~_19_;
  assign _20_ = ~(_03_ & _19_);
  assign _21_ = _03_ | _19_;
  assign _04_ = ~(_20_ & _21_);
  assign _22_ = ~(_05_ & _04_);
  assign _23_ = _05_ | _04_;
  assign _24_ = ~(_22_ & _23_);
  assign _06_ = ~_24_;
  assign _25_ = ~(_07_ & _24_);
  assign _26_ = _07_ | _24_;
  assign _27_ = _25_ & _26_;
  assign _08_ = ~_27_;
  assign _28_ = _09_ | _27_;
  assign _29_ = ~(_09_ & _27_);
  assign _10_ = ~(_28_ & _29_);
  assign _30_ = ~(_11_ & _10_);
  assign _31_ = _11_ | _10_;
  assign _32_ = ~(_30_ & _31_);
  assign _12_ = ~_32_;
  assign _33_ = ~(_13_ & _32_);
  assign _34_ = _13_ | _32_;
  assign _35_ = _33_ & _34_;
  assign _14_ = ~_35_;
  assign _36_ = _15_ | _35_;
  assign _37_ = ~(_15_ & _35_);
  assign _16_ = ~(_36_ & _37_);
  assign G = _06_;
  assign _07_ = H;
  assign I = _08_;
  assign _09_ = J;
  assign K = _10_;
  assign _11_ = L;
  assign M = _12_;
  assign _13_ = N;
  assign O = _14_;
  assign _15_ = P;
  assign Q = _16_;
  assign _01_ = B;
  assign _00_ = A;
  assign C = _02_;
  assign _03_ = D;
  assign E = _04_;
  assign _05_ = F;
endmodule
